server:
  port: 9889
spring:
  application:
    name: summit-srv-demo
  datasource:
    driverClassName: com.sap.db.jdbc.Driver
    url: jdbc:sap://localhost:30415/?currentschema=B47523F688504353A2B711CFD541F0E1
    username: SBSS_84528023222367180377430712230737653388588398032935590254405466575
    password: Qz9EBXYVz0NQbrol00_5yxbdtfIO7c1G5bbhDv9DEs_6NMu71lLrBCSB..j4XCF6vNt4DWp8xFkQ9_2m-mBgSxLsp2cFm35kyZGhHvbD_9bLOA3gf4gly_AVLDbj4Imr
  redis:
    database: 5
    host: 127.0.0.1
    password: 12345678
    port: 6379
    timeout: 3000
  jpa:
    properties:
      eclipselink.persistence-context.flush-mode: COMMIT
      eclipselink.weaving: static
      eclipselink.ddl-generation: none
      eclipselink.logging.timestamp: false
      eclipselink.logging.session: false
      eclipselink.logging.connection: false
      eclipselink.logging.thread: falsecd
      eclipselink.logging.level.transaction: ALL
      eclipselink.logging.level.sql: FINE
      eclipselink.logging.level.event: ALL
      eclipselink.logging.level.connection: ALL
      eclipselink.logging.level.query: FINE
      eclipselink.logging.level.cache: ALL
      eclipselink.logging.level: ALL
      eclipselink.logging.parameters: true
      eclipselink.cache.shared.default: false
      
# Eureka specifics
 
eureka:
  instance:
    hostname: localhost
    metadata-map:
      cluster: ems-demo-service
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/

blockchain.api.host: https://hyperledger-fabric.cfapps.sap.hana.ondemand.com/api/v1/chaincodes/f3758a10-4e9d-4d9d-9f34-5c7ddccb742f-com-sap-ems-emsDemo/latest
blockchain.api.service.key: {"type":"hyperledger-fabric","channelId":"devf3758a10-4e9d-4d9d-9f34-5c7ddccb742fems-a-channel","serviceUrl":"https://hyperledger-fabric.cfapps.sap.hana.ondemand.com/api/v1","documentationUrl":"https://api.sap.com/shell/discover/contentpackage/SCPBlockchainTechnologies/api/hyperledger_fabric","oAuth":{"clientId":"sb-4f963475-12a1-4125-883c-2f2f91c41e2d!b50|na-54bc25f3-f937-40b7-8b33-ffe240899cf0!b342","clientSecret":"05r8PEaVWCJozWOjRk1AxopU0wc=","url":"https://sap-csc-cd.authentication.sap.hana.ondemand.com","identityZone":"sap-csc-cd"}}